rteter

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -17,10 +17,10 @@ jobs:
          sleep 2 # Poczekaj chwilę na uruchomienie serwera
 
      - name: Run Cypress Test
-        id: cypress-test
-        run: |
-          npx cypress run --browser chrome || echo "Cypress tests failed"
-        continue-on-error: true
+       id: cypress-test
+       run: |
+        npx cypress run --browser chrome || echo "Cypress tests failed"
+       continue-on-error: true
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
