report failed tests

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -19,8 +19,9 @@ jobs:
      - name: Run Cypress Test
        id: cypress-test
        run: |
-        npx cypress run --browser chrome || echo "Cypress tests failed"
-       continue-on-error: true
+        npx cypress run --browser chrome
+        echo "CYPRESS_EXIT_CODE=$?" >> $GITHUB_ENV || true
+      #  continue-on-error: true
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
@@ -30,4 +31,7 @@ jobs:
        with:
          continue-on-error: true
          name: cypress-test-report
-         path: cypress/reports/html/index.html    
+         path: cypress/reports/html/index.html 
+     - name: Set failed status
+       if: env.CYPRESS_EXIT_CODE != '0'
+       run: echo "::error::Cypress tests failed"   
